name: HellespontusWorld
main: com.hellespontus.plugins.HellespontusWorld
version: 0.0.1
author: Pavel Naydenov

commands:
  point:
    desc: Show current player coondinates
    aliases: [p]
    usage: /point 
  blockline:
    desc: Create line from <N> blocks
    usage: /blockline <N>
    
permissions:
   hellespontus.*:
     description: Hellespontus world commands
     children:
       hellespontus.point: true
   hellespontus.point:
     description: Allow view player current position
     default: true
   hellespontus.blockline:
     description: Allow player create <N> block line
     default: false